# Generated by Django 5.1.4 on 2025-01-06 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_reg",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
