# Generated by Django 5.1.4 on 2025-01-07 02:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Rating",
                    models.IntegerField(
                        help_text="Rating (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("vol_ID", models.IntegerField()),
                (
                    "Department",
                    models.CharField(help_text="Department", max_length=255),
                ),
                ("Review_Content", models.TextField(help_text="Your Review")),
                ("Date_Submitted", models.DateTimeField(auto_now_add=True)),
                ("admin_user", models.CharField(max_length=255)),
                ("Sentiment", models.TextField(editable=False)),
                (
                    "Volunteer_First_Name",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "Volunteer_Last_Name",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                ("Admin_Response", models.TextField(blank=True, null=True)),
                (
                    "Volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["Date_Submitted", "-Rating"],
                "permissions": [
                    ("can_create_review", "Can create a review"),
                    ("can_edit_review", "Can edit a review"),
                    ("can_view_review", "Can view reviews"),
                ],
            },
        ),
    ]
