# Generated by Django 5.1.4 on 2025-01-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="vol_ID",
            field=models.IntegerField(null=True),
        ),
    ]
