# Generated by Django 5.1.4 on 2025-01-17 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_vol_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="Rating",
            field=models.IntegerField(
                help_text="(1-10)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="vol_ID",
            field=models.IntegerField(help_text="(Volunteer ID)", null=True),
        ),
    ]
